### PR TITLE
Add support ecr for read config

### PR DESCRIPTION
**Pull request by huuhait**
**Config**
Add support ecr for read config

### CODE REVIEW

**Comment by huuhait** [comment]
> Interesting idea, but it doesn't wok - see [here](https://travis-ci.org/github/imdrasil/jennifer.cr/jobs/690597891) (somewhy travis PR status update doesn't work ATM). As this PR introduces new behavior it should have tests

thanks, i will check it soon

**Comment by huuhait** [comment]
> Interesting idea, but it doesn't wok - see [here](https://travis-ci.org/github/imdrasil/jennifer.cr/jobs/690597891) (somewhy travis PR status update doesn't work ATM). As this PR introduces new behavior it should have tests

erc is macro so i cant use var for it :|

do you have any suggest?

https://github.com/crystal-lang/crystal/issues/6072

**Comment by cyangle** [comment]
This is how I did it.
```crystal
yaml_source = YAML.parse(ECR.render("config/database.yml.ecr"))
Jennifer::Config.configure do |config|
  config.from_yaml(yaml_source[Kemal.config.env])
end
```

**Comment by imdrasil** [comment]
I've added example from above to docs. Thank everyone for involvement :+1:

**Pull request closed without merging**
