### PR TITLE
Render a proper connection string without username or password

### PR DESCRIPTION
**Pull request by robacarp**
Allows Adapter::Base#connection_string to render a connection string such as postgres://localhost/db_name

previously, when given no username or password, it would render postgres://@localhost/db_name, which is an invalid connection string.

# Any background context you want to provide?

Re my issues getting started at #444 -- the first thing I tried to do was to connect to my local database without a username or password.

I ran into this with posgresql, but I did not have a local mysql installation available for testing.

# Release notes

**Config**
[BUGFIX] Now connection strings can be rendered without username or password.

### CODE REVIEW

**Review by imdrasil — APPROVED** [review]

**Comment by imdrasil** [comment]
@robacarp please address mysql related issue and we will be able to merge this PR

**Comment by imdrasil** [comment]
@robacarp it looks like failed tests aren't connected with your changes. I'll take a look on this weekend

**Comment by wJoenn** [comment]
@imdrasil Have you had time to look into what is blocking the CI ? 🤔

**Comment by imdrasil** [comment]
I was just an issue with the latest mysql version - my JSON patch to mysql driver causes very strange bug with `8.0.36`. Please merge in master branch and this issue should disappear

**Comment by robacarp** [comment]
all set

**Pull request merged**
