### PR TITLE
Crystal 0.34 compatibility.

### PR DESCRIPTION
**Pull request by didactic-drunk**
**General**

* add crystal `0.34` compatibility

### CODE REVIEW

**Comment by didactic-drunk** [comment]
This is technically 0.35 compatibiity and 0.34 warnings.

**Comment by imdrasil** [comment]
thank you for your PR, but this is already included in `release/0.9.0` which will be merged into master in a week or so

**Comment by didactic-drunk** [comment]
I guess I expected to see this on master with releases and release branches handling the current/older versions.

**Comment by imdrasil** [comment]
Agree with you - master's README should have explicit explanation about the latest stable release and possible future release branch

**Pull request closed without merging**
