### PR TITLE
Add Optimistic locking support

### PR DESCRIPTION
**Pull request by cyangle**
# What does this PR do?
Add Optimistic locking support
# Any background context you want to provide?
Rails active_record optimistic locking [doc](https://api.rubyonrails.org/classes/ActiveRecord/Locking/Optimistic.html)
# Release notes

Please fill the corresponding section regarding this pull request notes below instead of modifying `CHANGELOG.md` file. Please remove all redundant sections before posting request.

**Model**
Add Optimistic locking support via macro `with_optimistic_lock(column_name = lock_version)`

### CODE REVIEW

**Comment by cyangle** [comment]
This is a basic implementation of optimistic lock. Will refactor and add tests later. Just want to get it out early for feedback in case that I'm on the wrong path. @imdrasil

**Comment by imdrasil** [comment]
@cyangle thank you for your PR - great work. Just want to let you know that I'm reviewing this PR and will post my suggestions in a day or 2. :+1:

**Comment by imdrasil** [comment]
@cyangle finally I've finished with my proposal. What do you think about it?

**Comment by cyangle** [comment]
@imdrasil Your changes are great! Now the logic changes are limited to the OptimisticLocking module. 👍

**Pull request merged**
